### PR TITLE
Reduce build time

### PR DESCRIPTION
**Pull request by tsalo**
Changes proposed:
- Reduce the number of LDA iterations from 10000 to the default of 1000.
- Fit the GCLDA model ahead of time and use that instead of fitting on in the book build.
- Use `MKDADensity` instead of `MKDAChi2` in the `CorrelationDecoder` step.

The MDKA MCC step still takes over an hour, and I'm sure the subtraction analysis takes a while as well (I don't know the exact time for any other steps).

Currently it seems to clock in around 3 hours and 20 minutes.

### CODE REVIEW

**Comment by tsalo** [comment]
@ltetrel would 3 hours and 20 minutes be reasonable for a build? I can continue to streamline, but I think I would soon have to cut into more important elements of the book, such as multiple comparisons correction on meta-analyses.

**Comment by ltetrel** [comment]
How many CPUs are you using, and most importantly what is your cpu frequency ? the build environment has acces up to 2 logical CPUs https://ark.intel.com/content/www/us/en/ark/products/192446/intel-xeon-gold-6248-processor-27-5m-cache-2-50-ghz.html

**Comment by tsalo** [comment]
I have limited the build to 1 cpu, with one step using up to 4 cores. NiMARE should warn me if I try to use more cores than are available and adjust to the max allowed in that situation.

To be completely honest, I'm not really familiar with CPU Frequency, but after some Googling I checked the average CPU frequency for the job with `sacct` and it said 78.94M.

**Comment by ltetrel** [comment]
Ok so if you used just 1 cpu, we could try to re-build with your current  changes (dont 'forget to remove the jupyter cache then so it re-execute everything).
If for whatever reasons we are not able to build it, we will fall back to you pushing the jupyter cache files.

**Comment by ltetrel** [comment]
My only concern here is for the user experience, if they don't have access to cache files, the user execution on binder will take too much time. wdyt ?

**Comment by tsalo** [comment]
>Ok so if you used just 1 cpu, we could try to re-build with your current changes (dont 'forget to remove the jupyter cache then so it re-execute everything).

Awesome! I'll give it a try.

>My only concern here is for the user experience, if they don't have access to cache files, the user execution on binder will take too much time. wdyt ?

Does binder need to build the whole book each time users open it, or will it clone the built version from NeuroLibre?

**Comment by ltetrel** [comment]
No for the book it is okay, I am talking about the user who spawn a new binder environment. If they want to run the notebooks it will take a lot of time.

**Comment by ltetrel** [comment]
Anyway let me know when you push your code, so I make a build request.

**Comment by tsalo** [comment]
Will do. Should I set `execute_notebooks` to `"auto"` or `"force"`?

**Comment by ltetrel** [comment]
you can leave it to auto, anyway it will force it to auto when building

**Comment by tsalo** [comment]
Awesome. That's done as of 6b686ee, so I think you can request a new build.

**Pull request merged**
